POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ5Nzc4NDU5LCJ1c2VySWQiOjJ9.EZb3vMPj8rnw5GNmp2UOfvDy6XCBMAs0w8mYafzhVEw

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-06-04T18:30:00.000Z"
}

