POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NDk4MzI5MDQsInVzZXJJZCI6MX0.xVTdKIVi5zkUfmMqN4xodcfFQ0tf7oqrfDEuz3EB0d8

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-06-04T18:30:00.000Z"
}

